# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexeynabrodov/projects/mapgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexeynabrodov/projects/mapgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexeynabrodov/projects/mapgen/CMakeFiles /home/alexeynabrodov/projects/mapgen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexeynabrodov/projects/mapgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mapgen

# Build rule for target.
mapgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapgen
.PHONY : mapgen

# fast build rule for target.
mapgen/fast:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/build
.PHONY : mapgen/fast

#=============================================================================
# Target rules for targets named voronoi

# Build rule for target.
voronoi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voronoi
.PHONY : voronoi

# fast build rule for target.
voronoi/fast:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/build
.PHONY : voronoi/fast

Voronoi/src/BeachLine.o: Voronoi/src/BeachLine.cpp.o

.PHONY : Voronoi/src/BeachLine.o

# target to build an object file
Voronoi/src/BeachLine.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/BeachLine.cpp.o
.PHONY : Voronoi/src/BeachLine.cpp.o

Voronoi/src/BeachLine.i: Voronoi/src/BeachLine.cpp.i

.PHONY : Voronoi/src/BeachLine.i

# target to preprocess a source file
Voronoi/src/BeachLine.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/BeachLine.cpp.i
.PHONY : Voronoi/src/BeachLine.cpp.i

Voronoi/src/BeachLine.s: Voronoi/src/BeachLine.cpp.s

.PHONY : Voronoi/src/BeachLine.s

# target to generate assembly for a file
Voronoi/src/BeachLine.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/BeachLine.cpp.s
.PHONY : Voronoi/src/BeachLine.cpp.s

Voronoi/src/Cell.o: Voronoi/src/Cell.cpp.o

.PHONY : Voronoi/src/Cell.o

# target to build an object file
Voronoi/src/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Cell.cpp.o
.PHONY : Voronoi/src/Cell.cpp.o

Voronoi/src/Cell.i: Voronoi/src/Cell.cpp.i

.PHONY : Voronoi/src/Cell.i

# target to preprocess a source file
Voronoi/src/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Cell.cpp.i
.PHONY : Voronoi/src/Cell.cpp.i

Voronoi/src/Cell.s: Voronoi/src/Cell.cpp.s

.PHONY : Voronoi/src/Cell.s

# target to generate assembly for a file
Voronoi/src/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Cell.cpp.s
.PHONY : Voronoi/src/Cell.cpp.s

Voronoi/src/CircleEventQueue.o: Voronoi/src/CircleEventQueue.cpp.o

.PHONY : Voronoi/src/CircleEventQueue.o

# target to build an object file
Voronoi/src/CircleEventQueue.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/CircleEventQueue.cpp.o
.PHONY : Voronoi/src/CircleEventQueue.cpp.o

Voronoi/src/CircleEventQueue.i: Voronoi/src/CircleEventQueue.cpp.i

.PHONY : Voronoi/src/CircleEventQueue.i

# target to preprocess a source file
Voronoi/src/CircleEventQueue.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/CircleEventQueue.cpp.i
.PHONY : Voronoi/src/CircleEventQueue.cpp.i

Voronoi/src/CircleEventQueue.s: Voronoi/src/CircleEventQueue.cpp.s

.PHONY : Voronoi/src/CircleEventQueue.s

# target to generate assembly for a file
Voronoi/src/CircleEventQueue.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/CircleEventQueue.cpp.s
.PHONY : Voronoi/src/CircleEventQueue.cpp.s

Voronoi/src/Diagram.o: Voronoi/src/Diagram.cpp.o

.PHONY : Voronoi/src/Diagram.o

# target to build an object file
Voronoi/src/Diagram.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Diagram.cpp.o
.PHONY : Voronoi/src/Diagram.cpp.o

Voronoi/src/Diagram.i: Voronoi/src/Diagram.cpp.i

.PHONY : Voronoi/src/Diagram.i

# target to preprocess a source file
Voronoi/src/Diagram.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Diagram.cpp.i
.PHONY : Voronoi/src/Diagram.cpp.i

Voronoi/src/Diagram.s: Voronoi/src/Diagram.cpp.s

.PHONY : Voronoi/src/Diagram.s

# target to generate assembly for a file
Voronoi/src/Diagram.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Diagram.cpp.s
.PHONY : Voronoi/src/Diagram.cpp.s

Voronoi/src/Edge.o: Voronoi/src/Edge.cpp.o

.PHONY : Voronoi/src/Edge.o

# target to build an object file
Voronoi/src/Edge.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Edge.cpp.o
.PHONY : Voronoi/src/Edge.cpp.o

Voronoi/src/Edge.i: Voronoi/src/Edge.cpp.i

.PHONY : Voronoi/src/Edge.i

# target to preprocess a source file
Voronoi/src/Edge.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Edge.cpp.i
.PHONY : Voronoi/src/Edge.cpp.i

Voronoi/src/Edge.s: Voronoi/src/Edge.cpp.s

.PHONY : Voronoi/src/Edge.s

# target to generate assembly for a file
Voronoi/src/Edge.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/Edge.cpp.s
.PHONY : Voronoi/src/Edge.cpp.s

Voronoi/src/VoronoiDiagramGenerator.o: Voronoi/src/VoronoiDiagramGenerator.cpp.o

.PHONY : Voronoi/src/VoronoiDiagramGenerator.o

# target to build an object file
Voronoi/src/VoronoiDiagramGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/VoronoiDiagramGenerator.cpp.o
.PHONY : Voronoi/src/VoronoiDiagramGenerator.cpp.o

Voronoi/src/VoronoiDiagramGenerator.i: Voronoi/src/VoronoiDiagramGenerator.cpp.i

.PHONY : Voronoi/src/VoronoiDiagramGenerator.i

# target to preprocess a source file
Voronoi/src/VoronoiDiagramGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/VoronoiDiagramGenerator.cpp.i
.PHONY : Voronoi/src/VoronoiDiagramGenerator.cpp.i

Voronoi/src/VoronoiDiagramGenerator.s: Voronoi/src/VoronoiDiagramGenerator.cpp.s

.PHONY : Voronoi/src/VoronoiDiagramGenerator.s

# target to generate assembly for a file
Voronoi/src/VoronoiDiagramGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/Voronoi/src/VoronoiDiagramGenerator.cpp.s
.PHONY : Voronoi/src/VoronoiDiagramGenerator.cpp.s

imgui/imgui-SFML.o: imgui/imgui-SFML.cpp.o

.PHONY : imgui/imgui-SFML.o

# target to build an object file
imgui/imgui-SFML.cpp.o:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui-SFML.cpp.o
.PHONY : imgui/imgui-SFML.cpp.o

imgui/imgui-SFML.i: imgui/imgui-SFML.cpp.i

.PHONY : imgui/imgui-SFML.i

# target to preprocess a source file
imgui/imgui-SFML.cpp.i:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui-SFML.cpp.i
.PHONY : imgui/imgui-SFML.cpp.i

imgui/imgui-SFML.s: imgui/imgui-SFML.cpp.s

.PHONY : imgui/imgui-SFML.s

# target to generate assembly for a file
imgui/imgui-SFML.cpp.s:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui-SFML.cpp.s
.PHONY : imgui/imgui-SFML.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o

.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i

.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s

.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o

.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i

.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s

.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mapgen.dir/build.make CMakeFiles/mapgen.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mapgen"
	@echo "... voronoi"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... Voronoi/src/BeachLine.o"
	@echo "... Voronoi/src/BeachLine.i"
	@echo "... Voronoi/src/BeachLine.s"
	@echo "... Voronoi/src/Cell.o"
	@echo "... Voronoi/src/Cell.i"
	@echo "... Voronoi/src/Cell.s"
	@echo "... Voronoi/src/CircleEventQueue.o"
	@echo "... Voronoi/src/CircleEventQueue.i"
	@echo "... Voronoi/src/CircleEventQueue.s"
	@echo "... Voronoi/src/Diagram.o"
	@echo "... Voronoi/src/Diagram.i"
	@echo "... Voronoi/src/Diagram.s"
	@echo "... Voronoi/src/Edge.o"
	@echo "... Voronoi/src/Edge.i"
	@echo "... Voronoi/src/Edge.s"
	@echo "... Voronoi/src/VoronoiDiagramGenerator.o"
	@echo "... Voronoi/src/VoronoiDiagramGenerator.i"
	@echo "... Voronoi/src/VoronoiDiagramGenerator.s"
	@echo "... imgui/imgui-SFML.o"
	@echo "... imgui/imgui-SFML.i"
	@echo "... imgui/imgui-SFML.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

