#ifndef ECONOMY_H_
#define ECONOMY_H_

namespace Economy {
  const float POPULATION_GROWS = 0.04;
  const float POPULATION_GROWS_WEALTH_MODIFIER = 0.1;

  const float PACKAGES_PER_NICE = 20;
  const float PACKAGES_AGRO_POPULATION_MODIFIER = 0.04;

  const float PACKAGES_PER_MINERALS = 15;
  const float PACKAGES_MINERALS_POPULATION_MODIFIER = 0.03;

  const float CONSUME_AGRO_POPULATION_MODIFIER = 0.5;
  const float CONSUME_MINERALS_POPULATION_MODIFIER = 0.5;

  const float CONSUME_AGRO_WEALTH_MODIFIER = 0.1;
  const float CONSUME_MINERALS_WEALTH_MODIFIER = 0.1;

  const float CANT_BUY_AGRO = 0.3;
  const float CANT_BUY_MINERALS = 0.3;

  const float MINERALS_POPULATION_PRODUCE = 0.3;
  const float AGRO_POPULATION_PRODUCE = 0.4;

  const float PORT_FEE = 0.3;
}

class EconomyVars {
public:
  float POPULATION_GROWS;
  float POPULATION_GROWS_WEALTH_MODIFIER;

  float PACKAGES_PER_NICE;
  float PACKAGES_AGRO_POPULATION_MODIFIER;

  float PACKAGES_PER_MINERALS;
  float PACKAGES_MINERALS_POPULATION_MODIFIER;

  float CONSUME_AGRO_POPULATION_MODIFIER;
  float CONSUME_MINERALS_POPULATION_MODIFIER;

  float CONSUME_AGRO_WEALTH_MODIFIER;
  float CONSUME_MINERALS_WEALTH_MODIFIER;

  float CANT_BUY_AGRO;
  float CANT_BUY_MINERALS;

  float MINERALS_POPULATION_PRODUCE;
  float AGRO_POPULATION_PRODUCE;

  float PORT_FEE;

  EconomyVars();
};

#endif
