#ifndef ECONOMY_H_
#define ECONOMY_H_

namespace Economy {
  const float POPULATION_GROWS = 0.2f;
  const float POPULATION_GROWS_WEALTH_MODIFIER = 0.15f;

  const float PACKAGES_PER_NICE = 20.f;
  const float PACKAGES_AGRO_POPULATION_MODIFIER = 0.04f;

  const float PACKAGES_PER_MINERALS = 15.f;
  const float PACKAGES_MINERALS_POPULATION_MODIFIER = 0.03f;

  const float CONSUME_AGRO_POPULATION_MODIFIER = 0.5f;
  const float CONSUME_MINERALS_POPULATION_MODIFIER = 0.5f;

  const float CONSUME_AGRO_WEALTH_MODIFIER = 0.1f;
  const float CONSUME_MINERALS_WEALTH_MODIFIER = 0.1f;

  const float CANT_BUY_AGRO = 0.3f;
  const float CANT_BUY_MINERALS = 0.3f;

  const float MINERALS_POPULATION_PRODUCE = 0.3f;
  const float AGRO_POPULATION_PRODUCE = 0.4f;

  const float PORT_FEE = 0.3f;
  const float PRICE_CORRECTION = 0.1f;
}

class EconomyVars {
public:
  float POPULATION_GROWS;
  float POPULATION_GROWS_WEALTH_MODIFIER;

  float PACKAGES_PER_NICE;
  float PACKAGES_AGRO_POPULATION_MODIFIER;

  float PACKAGES_PER_MINERALS;
  float PACKAGES_MINERALS_POPULATION_MODIFIER;

  float CONSUME_AGRO_POPULATION_MODIFIER;
  float CONSUME_MINERALS_POPULATION_MODIFIER;

  float CONSUME_AGRO_WEALTH_MODIFIER;
  float CONSUME_MINERALS_WEALTH_MODIFIER;

  float CANT_BUY_AGRO;
  float CANT_BUY_MINERALS;

  float MINERALS_POPULATION_PRODUCE;
  float AGRO_POPULATION_PRODUCE;

  float PORT_FEE;
  float PRICE_CORRECTION;

  EconomyVars();
};

#endif
