#include "mapgen/Economy.hpp"

namespace Economy {
}

EconomyVars::EconomyVars() {
    POPULATION_GROWS = Economy::POPULATION_GROWS;
    POPULATION_GROWS_WEALTH_MODIFIER = Economy::POPULATION_GROWS_WEALTH_MODIFIER;

    PACKAGES_PER_NICE = Economy::PACKAGES_PER_NICE;
    PACKAGES_AGRO_POPULATION_MODIFIER = Economy::PACKAGES_AGRO_POPULATION_MODIFIER;

    PACKAGES_PER_MINERALS = Economy::PACKAGES_PER_MINERALS;
    PACKAGES_MINERALS_POPULATION_MODIFIER = Economy::PACKAGES_MINERALS_POPULATION_MODIFIER;

    CONSUME_AGRO_POPULATION_MODIFIER = Economy::CONSUME_AGRO_POPULATION_MODIFIER;
    CONSUME_MINERALS_POPULATION_MODIFIER = Economy::CONSUME_MINERALS_POPULATION_MODIFIER;

    CONSUME_AGRO_WEALTH_MODIFIER = Economy::CONSUME_AGRO_WEALTH_MODIFIER;
    CONSUME_MINERALS_WEALTH_MODIFIER = Economy::CONSUME_MINERALS_WEALTH_MODIFIER;

    CANT_BUY_AGRO = Economy::CANT_BUY_AGRO;
    CANT_BUY_MINERALS = Economy::CANT_BUY_MINERALS;

    MINERALS_POPULATION_PRODUCE = Economy::MINERALS_POPULATION_PRODUCE;
    AGRO_POPULATION_PRODUCE = Economy::AGRO_POPULATION_PRODUCE;

    PORT_FEE = Economy::PORT_FEE;
    PRICE_CORRECTION = Economy::PRICE_CORRECTION;
};
